Update Ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,8 +10,14 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Step 1 - Say Hello
-        run: echo "✅ Hello from step 1!"
+      - name: Step 1 - Check file
+        run: cat file.txt
 
-      - name: Step 2 - Say Bye
-        run: echo "✅ Bye from step 2!"
+      - name: Step 2 - Check for "error"
+        run: |
+          if grep -q "error" file.txt; then
+            echo "Fail"
+            exit 1
+          else
+            echo "Success"
+          fi
